### ISSUE TITLE
When cells are empty rows are not complete.

### ISSUE THREAD

**Issue by ghost** [VernierST/google-spreadsheet-to-php-array#1]
Say a spreadsheed is 5x2 cells.

1 2 3 4 5
1 2 3 4 5

Now when not all cells are populated the rows 'collapse'.

1345
12345

How can I populate cell 2 of row 1 with a space? Without assuming fixed width nor height?

**Comment by ghost** [comment]
Possible solution for fixed width sheets:

```
// The colums of which you want to ensure their presence in the array
$abc = array('A','B','C','D','E','F','G','H','I','J','K','L','M','N');
// Loop through the rows
foreach ($data_array as $row => $row_array) {

    foreach ($abc as $letter) {
        // If it is not set. Set it.    
        if (!isset($data_array[$row][$letter])){
            $data_array[$row][$letter] = '';
        }
    }
    // Because these newly set values get appended you need to sort them to the right position
    ksort($leden_array[$row]);

}
```

`

**Comment by davidlim** [comment]
Could you provide the URL of the spreadsheet you're trying to pull into PHP?

It is very possible that a cell is skipped, however, since it is rendered as a HTML table, I'll have to see the source to be sure.

And just to verify, you are using the v3 version of the function, right?

**Comment by ghost** [comment]
I'm using the other version that uses XML. Seemed faster to me. v3 also did
not work.

Op donderdag 18 februari 2016 heeft David Lim notifications@github.com
het volgende geschreven:

**Comment by davidlim** [comment]
I created the google_spreadsheet_to_array_v3 function because the original function stopped working after their API went to version 3. I'm surprised you got the original function to work at all. Since the API version 3 release, I haven't maintained the original function and cannot guarantee it to work. I left the function there for reference.

Your proposed solution could work, but that assumes that you only have columns to "N". Which makes it slightly limited. You are welcome to fork and implement it on your version and submit a pull request.

The google_spreadsheet_to_array_v3 function requires that the URL points to a published HTML version of the spreadsheet as it parses through a HTML table to get data. I would recommend this solution as Google can drop support to previous versions of the API without notice.
